version: "3.8"

services:
  frontapp:
    container_name: app-dev
    image: app-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
